In [1]:
# 3/28~4/8 - 넘파이, 판다스, ML
# 4/11~5/2 - 2차 프로젝트(빅데이터 활용 팀 프로젝트), 오전 ML/DL, 오후 조별 회의실
# 5/3~6/13 - 파이널 프로젝트(융합 프로젝트)
# 6/14-발표 및 수료식

# 넘파이 : 대량의 데이터를 빠르게 처리
# 판다스 : 데이터 분석
# 머신러닝(딥러닝) : 데이터 모델 -> 분류/예측

In [2]:
import numpy as np

In [3]:
np.__version__

'1.20.3'

# 제목 작성
## 제목 작성
### 제목 작성

[naver](http://www.naver.com)

__중요__
**중요합니다**
_조금 중요_
*조금 중요*

> 인용구를 사용할 수 있어요
>> 인용구 안에 인용구
>> 인용구 안에 수식을 써봅시다. $y=3x$
1. 첫번째
2. 두번째
3. 세번째
* 파이썬
* 넘파이
* 판다스
* 순서 없는 목록은 맨 앞에 *, +, - 기호를 작성한 다음 목록을 작성

* 수준1
    * 수준2
    * 수준3
        * 수준4

1. 첫번째
    * 수준1
    * 수준2
2. 두번째
    * 수준3
    * 수준4

***
---
<hr>

넘파이  
넘파이는 수치 연산 패키지입니다.  
판다스는 데이터 분석 패키지입니다.  
줄을 변경하고자 하는 경우에는 스페이스바를 2번 or br태그를 작성해도 됨<br>
줄이 바뀜

<span style="color:red">빨간색</span>  
<span style='font-size:30px'>30px</span>

![멀캠](https://www.multicampus.com/img/saas/main/logo/CUS0001/pc_main.png)

In [6]:
#파이썬 리스트 -> 넘파이 배열
arr=[1,2,3]

In [7]:
a=np.array(arr)
a

array([1, 2, 3])

In [22]:
#for i in range(5):
myarr=np.arange(10000000)   
mylist=list(range(10000000))

In [23]:
#mylist에 저장된 데이터를 2배 한 값을 mylist2에 저장
# mylist2=[]
# for i in mylist:
#     mylist2.append(i*2)
%time mylist2=[i*2 for i in mylist] #0.672초 소요

Wall time: 672 ms


In [24]:
%time myarr2=myarr*2 #0.016초 소요(수십 배 빠름)

Wall time: 16 ms


In [26]:
myarr2

array([       0,        2,        4, ..., 19999994, 19999996, 19999998])

In [28]:
np.random.seed(123)
np.random.rand(5) #0~1 난수 생성

array([0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897])

In [29]:
np.random.rand(3,2) #행렬

array([[0.42310646, 0.9807642 ],
       [0.68482974, 0.4809319 ],
       [0.39211752, 0.34317802]])

In [33]:
np.random.randint(1,5,size=10) #1<=정수난수<5
np.random.randint(1,5,size=(2,3)) #1<=정수난수<5

array([[1, 4, 3],
       [3, 3, 3]])

In [39]:
#표준정규분포(평균:0, 표준편차:1) 따르는 난수 생성
np.random.randn(10)
np.mean(np.random.randn(10))
np.std(np.random.randn(10))

np.random.randn(2,3) #2행3열

#평균:2, 표준편차:1.5인 정규분포
sigma, mu = 1.5, 2
sigma*np.random.randn(5)+mu

array([2.99848016, 0.65236559, 4.28549566, 0.35746031, 2.11884052])

In [41]:
#정규분포 난수 생성
#sigma*np.random.randn(5)+mu
np.random.normal(0,1,10) #평균:0, 표준편차:1, 데이터 :10

array([-0.07512059, -0.74081377,  0.07290724,  0.40308596,  1.47192937,
        0.30738422, -0.61122534, -0.39161981,  0.13997811,  0.09346083])

In [49]:
np.random.choice(5) #0~4 범위에서 난수 1개 생성
np.random.choice(5,5) #0~4 범위에서 난수 5개 생성
np.random.choice(5,10) #0~4 범위에서 난수 10개 생성
np.random.choice(5,(5,2))
#기본값 : 복원추출로 설정되어 있음

np.random.choice(5,5, replace=False) #비복원
np.random.choice(5,3, replace=False) #비복원


array([0, 1, 3])

In [54]:
#numpy:벡터화연산->속도빠름, list:벡터화연산못함=>속도느림
data=np.random.randn(2,3)
print(data)
print("="*50)
print(data*3)#numpy:벡터화연산->속도빠름
#벡터화연산?for문 사용 안함. 모든 요소에 대해 공통의 연산 수행

[[-0.12643756  1.17591077  0.68007153]
 [-1.00496715  0.64021868  1.37499063]]
[[-0.37931269  3.52773232  2.0402146 ]
 [-3.01490146  1.92065604  4.12497189]]


In [56]:
data * data #element wise product not equal matrix multiply

array([[0.01598646, 1.38276614, 0.46249729],
       [1.00995898, 0.40987996, 1.89059924]])

In [60]:
data.shape
data.dtype

dtype('float64')

In [63]:
data1=[6, 7.5, 8, 0, 1]
data1#리스트는 다양한 타입의 데이터가 저장

[6, 7.5, 8, 0, 1]

In [62]:
arr1=np.array(data1) #정수, 실수 => 실수로 통일 
arr1 #동일한 타입의 데이터가 저장

array([6. , 7.5, 8. , 0. , 1. ])

In [66]:
np.zeros(10)
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [68]:
np.ones(10)
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [72]:
np.ones(10)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [75]:
arr=np.arange(10)
arr.dtype
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
#배열에 저장된 자료의 타입을 변경
farr=arr.astype(np.float64)
farr
farr.dtype
arr=farr.astype(np.int64)
arr.dtype

dtype('int64')

In [79]:
arr=np.array([[1,2],[3,4]]) 
#배열:1차원배열(벡터),2차원배열(행렬), 3차원배열~(고차원배열)

In [84]:
arr*arr #element wise product
arr+arr
arr-arr
arr/arr
arr**2 #제곱
arr**0.5 #제곱근

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [88]:
arr=np.array([[1,2],[3,4]]) 

In [89]:
arr2=np.ones((2,2))

In [90]:
arr>arr2 #요소간 비교 연산

array([[False,  True],
       [ True,  True]])

In [94]:
np.arange(10)*2 #배열(1차원 벡터)*2(0차원 스칼라)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [96]:
arr=np.arange(10)*2 #브로드캐스팅(broad casting):크기를 동일하게 만든 다음 연산
#손오공(브로드캐스팅), 2 -> [2,2,...,2] 10개 -> element wise product

In [97]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [100]:
arr[5:8] #5번~8-1번 index
arr[5:8]=20
arr

array([ 0,  2,  4,  6,  8, 20, 20, 20, 16, 18])

In [102]:
arr2=arr[4:8]
arr2 #배열 -> 일부 slicing -> 새로운 배열 생성

array([ 8, 20, 20, 20])

In [108]:
arr=np.arange(10)*2
#arr=99 #기존 array는 제거되고, 새롭게 99라는 값을 arr변수에 저장
arr[:]=99 #일괄적으로 모든 값을 갱신

In [109]:
arr

array([99, 99, 99, 99, 99, 99, 99, 99, 99, 99])

In [112]:
arr=np.arange(10,16)
arr
arr2d=arr.reshape(2,3)#1차원 -> 2차원
arr2d

array([[10, 11, 12],
       [13, 14, 15]])

In [117]:
arr2d[0]
arr2d[1]
arr2d[0][2] #1행 3열 요소값 추출
arr2d[0,2]

12

In [121]:
arr=np.arange(1,25)
arr #1차원 배열 -> 3차원 배열
arr=arr.reshape(4,3,2) #4행 3열 2깊이

In [124]:
arr.ravel() #3차원 배열 -> 1차원 배열
arr.flatten()#3차원 배열 -> 1차원 배열

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [129]:
arr.shape #4행 3열 2깊이
arr.ndim #차원
arr.sum() #모든 요소의 합
arr #4*3*2

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [131]:
arr.sum(axis=None) #default, 전체 요소의 합
arr.sum(axis=0) #3*2

array([[40, 44],
       [48, 52],
       [56, 60]])

In [132]:
arr.sum(axis=1) #4*2

array([[ 9, 12],
       [27, 30],
       [45, 48],
       [63, 66]])

In [134]:
arr.sum(axis=2) #(4, 3, 2)->(4*3)
                #(행,열,깊이)
#다양한 데이터에 대해 선형대수 연산(sum)

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35],
       [39, 43, 47]])

In [137]:
arr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]])

In [136]:
arr.shape #(4, 3, 2)

(4, 3, 2)

axis=None 모든 요소의 합 -> 1개의 스칼라 값  
axis=0 x축 기준으로 여러개의 row를 1개로 합침  
axis=1 y축 기준으로 여러개의 row별로 column를 1개로 합침  
axis=2 z축 column의 depth값들을 1개로 합침  

In [141]:
arr=np.arange(11,20)
arr=arr.reshape(3,3)
arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [148]:
#배열명[행,열]
arr[0:2]
arr[:2]
arr[0:2,] # arr[0:2,:]
arr[0:2,1:]
arr[0:2,1:3]

array([[12, 13],
       [15, 16]])

In [157]:
#arr[2]# 1차원 배열  #arr[2,]  arr[2,:]
arr[2:]# arr[2:,:]# 2차원 배열
arr[2:3]
arr[2:3,:]

array([[17, 18, 19]])

In [158]:
arr

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [161]:
arr[:,:2]
arr[0:3,:2]
arr[0:3,0:2]

array([[11, 12],
       [14, 15],
       [17, 18]])

In [163]:
arr[1,:2] #1차원

array([14, 15])

In [164]:
arr[1:2,:2] #2차원

array([[14, 15]])

In [167]:
a=np.eye(4) #단위행렬(I), X*I=I*X=X
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [169]:
np.zeros_like(a)
np.ones_like(a)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [170]:
a=np.arange(10,50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [174]:
a
a[:] #순방향, a[시작:끝]
a[::]#순방향, a[시작:끝:방향]
a[::1] #순방향
a[::-1] #역방향

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

In [175]:
np.nonzero([0,1,2,0,3])

(array([1, 2, 4], dtype=int64),)