In [80]:
ns = ['1', '3', '5', '1', '3', '5', '1', '3', '5']

In [82]:
imsi=[]
for i in ns:
    if i not in imsi:
        imsi.append(i)
print(imsi)
# for i in ns:
#     print(i)
#     if ns.count(i)>1:
#         ns.remove(i)
#         print(ns)
#         print("="*50)

['3', '1', '5']


In [17]:
ns

['3', '1', '3', '5']

In [20]:
import numpy as np

In [21]:
names=np.array(['Bob','Joe','Will','Bob','Joe','Will'])

In [23]:
names=='Bob'

array([ True, False, False,  True, False, False])

In [25]:
data=np.random.randn(6,4)
data

array([[-0.02840924, -0.42067353,  0.57836342, -1.0642233 ],
       [-0.97343965, -1.59782344, -1.45674991,  0.13112656],
       [-0.00347091, -1.22192486,  1.17098253, -0.23367997],
       [ 0.1819364 ,  1.03202303,  2.03604504,  0.2225838 ],
       [-1.72391763,  1.12683022,  0.47304399, -1.18987802],
       [-1.70351566,  0.45276756,  0.14475148, -1.15631933]])

In [27]:
data[names=='Bob']

array([[-0.02840924, -0.42067353,  0.57836342, -1.0642233 ],
       [ 0.1819364 ,  1.03202303,  2.03604504,  0.2225838 ]])

In [28]:
names[names=='Bob']

array(['Bob', 'Bob'], dtype='<U4')

In [30]:
data[names=='Bob', 2:]

array([[ 0.57836342, -1.0642233 ],
       [ 2.03604504,  0.2225838 ]])

In [31]:
data[names=='Bob', 3]

array([-1.0642233,  0.2225838])

In [33]:
names != 'Bob'

array([False,  True,  True, False,  True,  True])

In [39]:
data[names != 'Bob'] # data[~(names=='Bob')]

array([[-0.97343965, -1.59782344, -1.45674991,  0.13112656],
       [-0.00347091, -1.22192486,  1.17098253, -0.23367997],
       [-1.72391763,  1.12683022,  0.47304399, -1.18987802],
       [-1.70351566,  0.45276756,  0.14475148, -1.15631933]])

In [36]:
~(names=='Bob') #연산 결과의 반대(~)

array([False,  True,  True, False,  True,  True])

In [40]:
data[~(names=='Bob')]

array([[-0.97343965, -1.59782344, -1.45674991,  0.13112656],
       [-0.00347091, -1.22192486,  1.17098253, -0.23367997],
       [-1.72391763,  1.12683022,  0.47304399, -1.18987802],
       [-1.70351566,  0.45276756,  0.14475148, -1.15631933]])

In [42]:
cond=names=='Bob'

In [45]:
cond
~cond
data[~cond]

array([[-0.97343965, -1.59782344, -1.45674991,  0.13112656],
       [-0.00347091, -1.22192486,  1.17098253, -0.23367997],
       [-1.72391763,  1.12683022,  0.47304399, -1.18987802],
       [-1.70351566,  0.45276756,  0.14475148, -1.15631933]])

In [48]:
#이름이 밥이거나 윌인 사람의 데이터를 추출
data[(names=='Bob')|(names=='Will')] # | : 또는(OR), & : 그리고(AND)

array([[-0.02840924, -0.42067353,  0.57836342, -1.0642233 ],
       [-0.00347091, -1.22192486,  1.17098253, -0.23367997],
       [ 0.1819364 ,  1.03202303,  2.03604504,  0.2225838 ],
       [-1.70351566,  0.45276756,  0.14475148, -1.15631933]])

In [51]:
data #음수만 출력하세요
data[data<0]

array([-0.02840924, -0.42067353, -1.0642233 , -0.97343965, -1.59782344,
       -1.45674991, -0.00347091, -1.22192486, -0.23367997, -1.72391763,
       -1.18987802, -1.70351566, -1.15631933])

In [52]:
data #음수를 모두 0으로 변경하세요
data[data<0]=0

In [53]:
data

array([[0.        , 0.        , 0.57836342, 0.        ],
       [0.        , 0.        , 0.        , 0.13112656],
       [0.        , 0.        , 1.17098253, 0.        ],
       [0.1819364 , 1.03202303, 2.03604504, 0.2225838 ],
       [0.        , 1.12683022, 0.47304399, 0.        ],
       [0.        , 0.45276756, 0.14475148, 0.        ]])

In [54]:
# names에서 이름이 Will이 아닌 사람들에 대한 index를 추출하여(0,1,3,4)
# data 배열의 해당 index 자료 값을 모두 10으로 변경하시오.

In [56]:
data[names!='Will']=10

In [58]:
arr=np.zeros((8,4))

In [60]:
for i in range(8):
    arr[i]=i+10
    print(arr[i])
    print("="*50)

[10. 10. 10. 10.]
[11. 11. 11. 11.]
[12. 12. 12. 12.]
[13. 13. 13. 13.]
[14. 14. 14. 14.]
[15. 15. 15. 15.]
[16. 16. 16. 16.]
[17. 17. 17. 17.]


In [61]:
arr

array([[10., 10., 10., 10.],
       [11., 11., 11., 11.],
       [12., 12., 12., 12.],
       [13., 13., 13., 13.],
       [14., 14., 14., 14.],
       [15., 15., 15., 15.],
       [16., 16., 16., 16.],
       [17., 17., 17., 17.]])

In [66]:
arr[4].shape
arr[4] #1차원

array([14., 14., 14., 14.])

In [68]:
arr[[4]] #2차원
arr[[4]].shape

(1, 4)

In [69]:
arr

array([[10., 10., 10., 10.],
       [11., 11., 11., 11.],
       [12., 12., 12., 12.],
       [13., 13., 13., 13.],
       [14., 14., 14., 14.],
       [15., 15., 15., 15.],
       [16., 16., 16., 16.],
       [17., 17., 17., 17.]])

In [72]:
#5행 4열 출력
arr[4,3] #0차원 스칼라, [] : 특정 요소값을 참조
arr[[4,3]] #2차원 5행과 4행을 참조, [[]]: 특정 행을 참조
arr[[4,3,0,6]]

array([[14., 14., 14., 14.],
       [13., 13., 13., 13.],
       [10., 10., 10., 10.],
       [16., 16., 16., 16.]])

In [76]:
arr[[5,3]]
# [[15., 15., 15., 15.],
# [13., 13., 13., 13.]]
arr[[-3, -5]]

array([[15., 15., 15., 15.],
       [13., 13., 13., 13.]])

In [83]:
arr=np.arange(10,42).reshape(8,4)
arr

array([[10, 11, 12, 13],
       [14, 15, 16, 17],
       [18, 19, 20, 21],
       [22, 23, 24, 25],
       [26, 27, 28, 29],
       [30, 31, 32, 33],
       [34, 35, 36, 37],
       [38, 39, 40, 41]])

In [87]:
arr[[1,5,7,2]]

array([[14, 15, 16, 17],
       [30, 31, 32, 33],
       [38, 39, 40, 41],
       [18, 19, 20, 21]])

In [88]:
arr[[1,5,7,2],[0]]#1,5,7,2행의 0열 값 추출
arr[[1,5,7,2],[0,3,1,2]]#14,33,39,20

array([14, 33, 39, 20])

In [90]:
arr[[1,5,7,2]]

array([[14, 15, 16, 17],
       [30, 31, 32, 33],
       [38, 39, 40, 41],
       [18, 19, 20, 21]])

In [94]:
#[0,1,2,3] => [0,3,1,2]
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[14, 17, 15, 16],
       [30, 33, 31, 32],
       [38, 41, 39, 40],
       [18, 21, 19, 20]])

In [97]:
arr=np.arange(15).reshape(3,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
arr.T.shape
arr.T.T.shape

(3, 5)

In [102]:
arr.shape #(3,5)
arr.T.shape#(5,3)

(5, 3)

In [105]:
#행렬의 곱셈
np.dot(arr.T, arr) #5,3  3,5 => 5*5 행렬
np.dot(arr, arr.T) #3,5 5,3 => 3*3 행렬

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [108]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [110]:
np.sqrt(arr)
np.exp(arr) #2.718 자연상수의 제곱

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [112]:
x=np.random.randn(8)
y=np.random.randn(8)

In [113]:
x

array([ 0.13336043, -0.48745711,  1.05363277,  0.46301174, -0.33161611,
       -1.2024254 ,  0.16805828, -0.254334  ])

In [114]:
y

array([ 0.49682715, -0.28684321,  2.05790873, -0.11265404,  0.2087964 ,
       -1.11452667,  1.23190367,  0.64779854])

In [115]:
#x,y 배열의 동일한 위치에 저장된 값들을 비교하여 큰 값을 출력
#[0.49682715, -0.28684321, ... , 0.64779854]

In [117]:
y[x<y]

array([ 0.49682715, -0.28684321,  2.05790873,  0.2087964 , -1.11452667,
        1.23190367,  0.64779854])

In [120]:
x<y

array([ True,  True,  True, False,  True,  True,  True,  True])

In [122]:
x[x<y]=y[x<y]

In [123]:
x

array([ 0.49682715, -0.28684321,  2.05790873,  0.46301174,  0.2087964 ,
       -1.11452667,  1.23190367,  0.64779854])

In [125]:
np.maximum(x,y)
np.minimum(x,y)

array([ 0.49682715, -0.28684321,  2.05790873, -0.11265404,  0.2087964 ,
       -1.11452667,  1.23190367,  0.64779854])

In [127]:
arr=np.random.randn(7)*5
arr

array([-2.47754365, -4.62952122, -0.37753868,  0.71651323,  0.58031097,
       -2.43666275, -4.48621388])

In [130]:
np.modf(arr) #정수와 실수부분을 분리, 분리 결과가 튜플
np.modf(arr)[0]
np.modf(arr)[1]

array([-2., -4., -0.,  0.,  0., -2., -4.])

In [132]:
remainder, whole_part=np.modf(arr)

In [137]:
points=np.arange(-5,5)
points.shape
points

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [139]:
res=np.meshgrid(points,points) #1차원 배열 2개(x,y)를 입력받아서 짝을 구성하여 2차원 배열 2개 생성
res[0]
res[1]

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

In [140]:
x,y=np.meshgrid(points,points)

In [149]:
x.shape
np.sqrt(x**2+y**2)

array([[7.07106781, 6.40312424, 5.83095189, 5.38516481, 5.09901951,
        5.        , 5.09901951, 5.38516481, 5.83095189, 6.40312424],
       [6.40312424, 5.65685425, 5.        , 4.47213595, 4.12310563,
        4.        , 4.12310563, 4.47213595, 5.        , 5.65685425],
       [5.83095189, 5.        , 4.24264069, 3.60555128, 3.16227766,
        3.        , 3.16227766, 3.60555128, 4.24264069, 5.        ],
       [5.38516481, 4.47213595, 3.60555128, 2.82842712, 2.23606798,
        2.        , 2.23606798, 2.82842712, 3.60555128, 4.47213595],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.        , 4.        , 3.        , 2.        , 1.        ,
        0.        , 1.        , 2.        , 3.        , 4.        ],
       [5.09901951, 4.12310563, 3.16227766, 2.23606798, 1.41421356,
        1.        , 1.41421356, 2.23606798, 3.16227766, 4.12310563],
       [5.38516481, 4.47213595, 3.6055512

In [ ]:
meshgrid함수를 활용
array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [158]:
x=np.arange(3) #array([0, 1, 2])
x
y=np.arange(5) #array([0, 1, 2, 3, 4])
y
xx, yy=np.meshgrid(x,y)

In [153]:
# a=np.arange(0,5)
# x,y=np.meshgrid(a,a)
# x
# y
# x[:,0:3]
# y[:,0:3]

# x,y=np.meshgrid(np.arange(0,5),np.arange(0,5))
# x=x[:,0:3]
# y=y[:,0:3]


array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [159]:
xx

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [160]:
yy

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [164]:
[list(zip(x,y)) for x,y in zip(xx,yy)] #x:[0, 1, 2], y:[0, 0, 0]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [163]:
for p in zip(xx,yy):
    print(p)

(array([0, 1, 2]), array([0, 0, 0]))
(array([0, 1, 2]), array([1, 1, 1]))
(array([0, 1, 2]), array([2, 2, 2]))
(array([0, 1, 2]), array([3, 3, 3]))
(array([0, 1, 2]), array([4, 4, 4]))


In [162]:
n=[1,2,3]
k=[4,5,6]
# for p in zip(n,k):
#     print(p)
for i in range(3):
    p=(n[i], k[i])
    print(p)

(1, 4)
(2, 5)
(3, 6)


In [165]:
xarr=np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr=np.array([2.1, 2.2, 2.3, 2.4, 2.5])

In [166]:
cond=np.array([True, False, True, True, False])

In [171]:
[(x if z else y) for x,y,z in zip(xarr,yarr, cond)]

[1.1, 2.2, 1.3, 1.4, 2.5]

In [172]:
#np.where(조건, 참, 거짓)
np.where(cond, xarr, yarr)

array([1.1, 2.2, 1.3, 1.4, 2.5])

In [173]:
arr=np.random.randn(4,4)

In [175]:
arr
arr>1

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False]])

In [177]:
arr[arr>1]

array([1.30195244])

In [180]:
arr
np.where(arr>0,1,0)
np.where(arr>0,1,arr)

array([[ 1.        , -0.00793893,  1.        , -0.47527805],
       [-0.21985459, -0.91746287,  1.        ,  1.        ],
       [-0.55336666, -0.97814524,  1.        , -1.25843346],
       [-0.28277648,  1.        , -0.241768  , -1.45960041]])

In [181]:
np.random.seed(123)

In [182]:
arr=np.random.randn(5,4)
arr

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ]])

In [186]:
arr.mean() #np.mean(arr)
arr

array([[-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471],
       [-0.57860025,  1.65143654, -2.42667924, -0.42891263],
       [ 1.26593626, -0.8667404 , -0.67888615, -0.09470897],
       [ 1.49138963, -0.638902  , -0.44398196, -0.43435128],
       [ 2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ]])

In [188]:
#각 행에 대한 데이터의 평균 or 합계, 열 방향으로 이동해 가면서 평균/합계 구해야 함
arr.mean(axis=1)
arr.mean(axis=0)

array([ 0.65980502,  0.66598513, -0.45250299, -0.41561624])

In [191]:
arr=np.arange(1,8)
arr.cumsum() #누적합
arr.cumprod() #누적곱(팩터리얼), 7!

array([   1,    2,    6,   24,  120,  720, 5040], dtype=int32)

In [192]:
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
arr.cumsum() #전체 데이터의 누적합
arr.cumsum(axis=1) #열 방향으로 이동해가면서 누적합(좌->우)
arr.cumsum(axis=0) #행            "         "      (위->아래)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]], dtype=int32)

In [198]:
arr.mean()
arr.var() #분산
arr.std() #표준편차(분산의 제곱근)

2.581988897471611

In [200]:
arr  #5보다 큰 수의 개수, 5보다 큰 수의 합 출력

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [203]:
arr[arr>5].sum()

30

In [213]:
#sum(sum(arr>5))
#sum(arr[arr>5])
arr[arr>5].sum()
len(arr[arr>5])


4

In [216]:
(arr>5).sum() #False=0, True=1

4

In [218]:
arr
arr=np.where(arr>5, True, False)

In [219]:
arr

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [221]:
arr.any() #하나이상 true -> true
arr.all()

False

In [222]:
arr=np.random.randn(6)
arr.sort()

In [223]:
arr

array([-1.25388067, -0.93583387, -0.6377515 ,  0.73736858,  1.17582904,
        1.49073203])

In [224]:
arr=np.random.randn(5,3)
arr

array([[ 0.9071052 , -1.4286807 , -0.14006872],
       [-0.8617549 , -0.25561937, -2.79858911],
       [-1.7715331 , -0.69987723,  0.92746243],
       [-0.17363568,  0.00284592,  0.68822271],
       [-0.87953634,  0.28362732, -0.80536652]])

In [225]:
arr.sort() #오름차순정렬(열방향, axis=1, default), 행방향(axis=0)
arr

array([[-1.4286807 , -0.14006872,  0.9071052 ],
       [-2.79858911, -0.8617549 , -0.25561937],
       [-1.7715331 , -0.69987723,  0.92746243],
       [-0.17363568,  0.00284592,  0.68822271],
       [-0.87953634, -0.80536652,  0.28362732]])

In [226]:
arr

array([[-1.4286807 , -0.14006872,  0.9071052 ],
       [-2.79858911, -0.8617549 , -0.25561937],
       [-1.7715331 , -0.69987723,  0.92746243],
       [-0.17363568,  0.00284592,  0.68822271],
       [-0.87953634, -0.80536652,  0.28362732]])

In [227]:
arr.sort(axis=0)

In [228]:
arr

array([[-2.79858911, -0.8617549 , -0.25561937],
       [-1.7715331 , -0.80536652,  0.28362732],
       [-1.4286807 , -0.69987723,  0.68822271],
       [-0.87953634, -0.14006872,  0.9071052 ],
       [-0.17363568,  0.00284592,  0.92746243]])

In [229]:
#넘파이는 오름차순 정렬은 함수가 있지만, 내림차순 정렬은 없음

In [230]:
arr

array([[-2.79858911, -0.8617549 , -0.25561937],
       [-1.7715331 , -0.80536652,  0.28362732],
       [-1.4286807 , -0.69987723,  0.68822271],
       [-0.87953634, -0.14006872,  0.9071052 ],
       [-0.17363568,  0.00284592,  0.92746243]])

In [231]:
arr[::-1] #내림차순정렬(오름차순 결과에 대해 뒤에서부터 참조)

array([[-0.17363568,  0.00284592,  0.92746243],
       [-0.87953634, -0.14006872,  0.9071052 ],
       [-1.4286807 , -0.69987723,  0.68822271],
       [-1.7715331 , -0.80536652,  0.28362732],
       [-2.79858911, -0.8617549 , -0.25561937]])

In [232]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Joe', 'Will'], dtype='<U4')

In [235]:
#유일한 이름만 출력
np.array(list(set(names)))
np.unique(names) #자동정렬

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [240]:
sorted(set(names))

['Bob', 'Joe', 'Will']

In [241]:
arr=np.array([6,0,0,3,2,5])

In [243]:
[2,3,6] #arr의 각 원소가 2또는 3또는 6인지 조사 -> True/False
np.in1d(arr,[2,3,6])

array([ True, False, False,  True,  True, False])

In [244]:
arr[np.in1d(arr,[2,3,6])]

array([6, 3, 2])

In [246]:
a=np.array([1,2,3])
b=np.array([10,20,30])

In [248]:
#a가 2이면서 b가 10보다 크면 True, 아니면 False출력
np.where((a==2)&(b>10), True, False )
(a==2)&(b>10)

array([False,  True, False])

In [251]:
(a==2)&(b>10)

array([False,  True, False])

In [252]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
#행의 개수, 열의 개수 출력

In [255]:
a.shape
a.shape[0]
a.shape[1]

3

In [256]:
a=np.ones((2,3))
b=np.zeros((2,2))

In [257]:
a

array([[1., 1., 1.],
       [1., 1., 1.]])

In [258]:
b

array([[0., 0.],
       [0., 0.]])

In [259]:
np.hstack([a,b]) #horizontal(좌우 연결, 행의 개수 동일)

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

In [261]:
#np.vstack([a,b]) #vertical, 에러발생:열의 개수 동일
b=np.zeros((2,3))
np.vstack([a,b])

array([[1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [262]:
a=np.arange(6).reshape(2,3)

In [264]:
np.tile(a,2) #동일한 배열을 반복하여 연결, 좌우 방향으로 2번연결
np.tile(a,(3,2))#동일한 배열을 반복하여 연결, 위아래 3번, 좌우 방향으로 2번연결

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5]])

In [266]:
ret=np.unique([1,1,3,3,5])

In [269]:
ret[0]
ret

array([1, 3, 5])

In [270]:
ret=np.unique([1,1,3,3,5], return_counts=True)
ret

(array([1, 3, 5]), array([2, 2, 1], dtype=int64))

In [271]:
ret[0]

array([1, 3, 5])

In [272]:
ret[1]

array([2, 2, 1], dtype=int64)

In [ ]:
# 브로드캐스팅:크기가 서로 다른 배열간에 연산이 가능하도록, 크기가 작은 배열을 반복해서 확장하여
# 크기가 큰 배열과 크기를 맞추고 난 다음 연산을 수행

In [273]:
np.array([1,2,3])+5 #5 -> [5,5,5]

array([6, 7, 8])

In [274]:
x=np.array([1,2,3])

In [276]:
np.ones_like(x)*5

array([5, 5, 5])

In [277]:
x+np.ones_like(x)*5 #np.array([1,2,3])+5

array([6, 7, 8])

In [278]:
x

array([1, 2, 3])

In [281]:
np.random.shuffle(x)

In [282]:
x

array([1, 3, 2])

In [283]:
#판다스:데이터분석, 구조:시리즈, 데이터프레임
#시계열, 표

In [284]:
import pandas as pd

In [ ]:
#시리즈? 1차원 배열와 거의 유사, 차이점:시리즈에는 데이터에 index가 붙어있다
# 1차원배열:데이터가 나열된 구조
# 시리즈:index가 있는 데이터가 나열된 구조, 데이터를 리스트나 배열에 넣고나서 시리즈함수에 전달해주면 생성됨

In [287]:
pd.Series([1000, 300, 150, 200])
pd.Series(range(10,14))

0    10
1    11
2    12
3    13
dtype: int64

In [286]:
s=pd.Series([1000, 300, 150, 200], 
            index=['서울','부산','인천','대구']) #문자숫자 모두 가능
s

서울    1000
부산     300
인천     150
대구     200
dtype: int64

In [288]:
s.index #시리즈의 인덱스 접근

Index(['서울', '부산', '인천', '대구'], dtype='object')

In [289]:
s.values#시리즈의 데이터 추출

array([1000,  300,  150,  200], dtype=int64)

In [290]:
s

서울    1000
부산     300
인천     150
대구     200
dtype: int64

In [291]:
s.name="인구데이터"#시리즈 데이터에 대한 이름 부여

In [292]:
s

서울    1000
부산     300
인천     150
대구     200
Name: 인구데이터, dtype: int64

In [294]:
s.index.name="도시명"

In [295]:
s

도시명
서울    1000
부산     300
인천     150
대구     200
Name: 인구데이터, dtype: int64

In [297]:
#시리즈 연산:넘파이 배열처럼 벡터화 연산을 수행
s/1000

도시명
서울    1.00
부산    0.30
인천    0.15
대구    0.20
Name: 인구데이터, dtype: float64

In [301]:
s['부산']
s[1]

300

In [300]:
s
#눈에는 보이지 않지만, 내부적으로 시리즈에는 절대 index(0번부터 시작하여 번호가 부여)가 존재.
#ex) 서울 index는 절대 index가 0

도시명
서울    1000
부산     300
인천     150
대구     200
Name: 인구데이터, dtype: int64

In [306]:
s[[1, 3, 0]] #절대 index
s[['부산','대구','서울']]

도시명
부산     300
대구     200
서울    1000
Name: 인구데이터, dtype: int64

In [308]:
#인구가 150만 초과, 300만 이하인 데이터 출력
s[(s>150) & (s<=300)]
s[(s.values>150)&(s.values<=300)]


도시명
부산    300
대구    200
Name: 인구데이터, dtype: int64

In [309]:
s

도시명
서울    1000
부산     300
인천     150
대구     200
Name: 인구데이터, dtype: int64

In [312]:
s[1]
s[1:3]#1번과 2번까지 참조, 3번은 불포함
s['부산':'대구']#대구까지도 포함되어 참조

도시명
부산    300
인천    150
대구    200
Name: 인구데이터, dtype: int64

In [314]:
s.부산 #점찍고 접근 가능, 시리즈명.인덱스명

300

In [315]:
s #in연산자 : 특정 인덱스에 해당되는 자료가 존재?

도시명
서울    1000
부산     300
인천     150
대구     200
Name: 인구데이터, dtype: int64

In [317]:
'광주' in s

False

In [318]:
d={'국어':90,'영어':100,'수학':95}

In [319]:
d

{'국어': 90, '영어': 100, '수학': 95}

In [320]:
d['국어']

90

In [322]:
#딕셔너리의 예
for k,v in d.items():
    print(v)    

90
100
95


In [324]:
for k,v in s.items():
    print(k,v)

서울 1000
부산 300
인천 150
대구 200


In [325]:
d

{'국어': 90, '영어': 100, '수학': 95}

In [326]:
s2=pd.Series(d)
s2

국어     90
영어    100
수학     95
dtype: int64

In [327]:
s

도시명
서울    1000
부산     300
인천     150
대구     200
Name: 인구데이터, dtype: int64

In [328]:
s2 = pd.Series({"서울": 9631482, "부산": 3393191, "인천": 2632035, "대전": 1490158},
               index=["부산", "서울", "인천", "대전"])

In [329]:
s2

부산    3393191
서울    9631482
인천    2632035
대전    1490158
dtype: int64

In [330]:
s-s2 #같은 인덱스끼리 여산 -> NaN, float

대구          NaN
대전          NaN
부산   -3392891.0
서울   -9630482.0
인천   -2631885.0
dtype: float64

In [331]:
s.values

array([1000,  300,  150,  200], dtype=int64)

In [332]:
s2.values

array([3393191, 9631482, 2632035, 1490158], dtype=int64)

In [333]:
s.values-s2.values#값들끼리 연산하게되면 인덱스 정보는 무시(주의)

array([-3392191, -9631182, -2631885, -1489958], dtype=int64)

In [337]:
ds=s-s2
ds

대구          NaN
대전          NaN
부산   -3392891.0
서울   -9630482.0
인천   -2631885.0
dtype: float64

In [338]:
ds.notnull() #null은 NaN을 의미함.

대구    False
대전    False
부산     True
서울     True
인천     True
dtype: bool

In [340]:
rs=ds[ds.notnull() ]

In [341]:
rs

부산   -3392891.0
서울   -9630482.0
인천   -2631885.0
dtype: float64

In [343]:
#데이터 갱신
rs['서울']=10

In [344]:
#데이터 제거
del rs['서울']

In [345]:
rs

부산   -3392891.0
인천   -2631885.0
dtype: float64

In [347]:
from sklearn.datasets import load_iris
#설치 방법 : pip install scikit-learn

In [349]:
iris=load_iris() #ㄷ기셔너리

In [351]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [354]:
iris['data']
iris.data
iris.data.shape #(150, 4)

(150, 4)

In [356]:
iris.data[0]

array([5.1, 3.5, 1.4, 0.2])

In [357]:
iris.data
[5.1, 3.5, 1.4, 0.2]
[4.9, 3. , 1.4, 0.2]
ecu_dist=np.sqrt((5.1-4.9)^2+...( 0.2-0.2)^2)

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3