In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
a=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])
a[1].argsort()
#a[:,a[1].argsort()]
a[:,[0, 3, 1, 2]]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [10]:
a=[4,3,5,7,6,8]
indices=[0,1,4,-1]
indices2=[[0,1],[4,-1]]

In [13]:
a=np.array(a)

In [14]:
#numpy.take() : index를 사용해서 배열의 요소를 추출
np.take(a, indices)
a.take(indices)

array([4, 3, 6, 8])

In [11]:
np.take(a, indices2)#인덱스의 차원과 동일한 차원을 갖는다

array([[4, 3],
       [6, 8]])

In [15]:
a=np.array([[  1,    2,    3,    4],
       [ 46,   99,  100,   71],
       [ 81,   59,   90,  100]])

In [18]:
score_rank=a[1].argsort()
score_rank

array([0, 3, 1, 2], dtype=int64)

In [20]:
a.take(score_rank, axis=1)

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [22]:
import pandas as pd
a=pd.Series([80,90,70,50], index=['수학','영어','사회','과학'])
b=pd.Series([100,80,50,20], index=['국어','영어','수학','체육'])

In [24]:
type(a+b)

pandas.core.series.Series

In [34]:
np.random.choice(45, 6, replace=False)+1

array([ 1, 20, 44, 37, 17, 10])

In [56]:
a=np.array([1.5, 0.2, 4.2, 2.5])

In [ ]:
#오름차순, 내림차순, argsort()사용

In [40]:
a[-(a.argsort())]    
a[(a.argsort())[::-1]]


array([4.2, 2.5, 1.5, 0.2])

In [42]:
a[(a.argsort())[::-1]]

array([4.2, 2.5, 1.5, 0.2])

In [44]:
a[a.argsort()]
a[a.argsort()[::-1]]


array([1, 0, 3, 2], dtype=int64)

In [ ]:
np.argsort(a)
np.argsort(a)[::-1]


In [45]:
a.sort()


In [46]:
a

array([0.2, 1.5, 2.5, 4.2])

In [47]:
a.take((-a).argsort())


array([4.2, 2.5, 1.5, 0.2])

In [48]:
a

array([0.2, 1.5, 2.5, 4.2])

In [49]:
-a

array([-0.2, -1.5, -2.5, -4.2])

In [50]:
(-a).argsort()

array([3, 2, 1, 0], dtype=int64)

In [51]:
a.take((-a).argsort())


array([4.2, 2.5, 1.5, 0.2])

In [52]:
a[~a.argsort()]


array([4.2, 2.5, 1.5, 0.2])

In [59]:
~a.argsort()
a[~a.argsort()]


array([4.2, 2.5, 1.5, 0.2])

In [63]:
obj=pd.Series([3,1,-5,2], index=['d','a','b','c'])
obj

d    3
a    1
b   -5
c    2
dtype: int64

In [64]:
obj.values
obj.index

Index(['d', 'a', 'b', 'c'], dtype='object')

In [66]:
obj['b']
obj['b']=-4

In [67]:
obj

d    3
a    1
b   -4
c    2
dtype: int64

In [69]:
obj[['b','a','c']]


b   -4
a    1
c    2
dtype: int64

In [70]:
'k' in obj

False

In [71]:
sdata={'Seoul':1000, 'Incheon':200, 'Gwangju':100, 'Busan':300}

In [73]:
obj2=pd.Series(sdata) #dictionary의 key가 series의 행index가 됨, value가 data가 됨

In [74]:
obj2['Gwangju']

100

In [75]:
cities=['Seoul', 'Incheon', 'Suwon', 'Daejon']

In [78]:
pd.Series(cities)
pd.Series(sdata)

Seoul      1000
Incheon     200
Gwangju     100
Busan       300
dtype: int64

In [81]:
obj3=pd.Series(sdata, index=cities)
obj3

Seoul      1000.0
Incheon     200.0
Suwon         NaN
Daejon        NaN
dtype: float64

In [82]:
pd.isnull(obj3)

Seoul      False
Incheon    False
Suwon       True
Daejon      True
dtype: bool

In [83]:
pd.notnull(obj3)

Seoul       True
Incheon     True
Suwon      False
Daejon     False
dtype: bool

In [84]:
obj3.isnull()

Seoul      False
Incheon    False
Suwon       True
Daejon      True
dtype: bool

In [87]:
for k, v in obj3.items():
    print(v)

1000.0
200.0
nan
nan


In [90]:
obj3['Suwon']=100

In [91]:
obj3

Seoul      1000.0
Incheon     200.0
Suwon       100.0
Daejon        NaN
dtype: float64

In [92]:
del obj3['Daejon']

In [93]:
obj3

Seoul      1000.0
Incheon     200.0
Suwon       100.0
dtype: float64

In [99]:
data = {
    "2015": [9904312, 3448737, 2890451, 2466052],
    "2010": [9631482, 3393191, 2632035, 2431774],
    "2005": [9762546, 3512547, 2517680, 2456016],
    "2000": [9853972, 3655437, 2466338, 2473990],
    "지역": ["수도권", "경상권", "수도권", "경상권"],
    "2010-2015 증가율": [0.0283, 0.0163, 0.0982, 0.0141]
}
idx = ["서울", "부산", "인천", "대구"]
cols = ["지역", "2015", "2010", "2005", "2000", "2010-2015 증가율"]

In [96]:
pd.Series(data)

2015             [9904312, 3448737, 2890451, 2466052]
2010             [9631482, 3393191, 2632035, 2431774]
2005             [9762546, 3512547, 2517680, 2456016]
2000             [9853972, 3655437, 2466338, 2473990]
지역                               [수도권, 경상권, 수도권, 경상권]
2010-2015 증가율        [0.0283, 0.0163, 0.0982, 0.0141]
dtype: object

In [101]:
#데이터프레임:1개 이상의 시리즈들이 모여서 구성
df=pd.DataFrame(data, index=idx, columns=cols) #키->열 이름(index)

In [102]:
df

지역     2015     2010     2005     2000  2010-2015 증가율
서울  수도권  9904312  9631482  9762546  9853972         0.0283
부산  경상권  3448737  3393191  3512547  3655437         0.0163
인천  수도권  2890451  2632035  2517680  2466338         0.0982
대구  경상권  2466052  2431774  2456016  2473990         0.0141

In [105]:
df.values #dataframe 값(데이터)-> array
df.index #행인덱스
df.columns #열인덱스

Index(['지역', '2015', '2010', '2005', '2000', '2010-2015 증가율'], dtype='object')

In [110]:
df.index.name='도시명'
df.columns.name='특징'

In [111]:
df

특징    지역     2015     2010     2005     2000  2010-2015 증가율
도시명                                                        
서울   수도권  9904312  9631482  9762546  9853972         0.0283
부산   경상권  3448737  3393191  3512547  3655437         0.0163
인천   수도권  2890451  2632035  2517680  2466338         0.0982
대구   경상권  2466052  2431774  2456016  2473990         0.0141

In [112]:
df.T

도시명                 서울       부산       인천       대구
특징                                               
지역                 수도권      경상권      수도권      경상권
2015           9904312  3448737  2890451  2466052
2010           9631482  3393191  2632035  2431774
2005           9762546  3512547  2517680  2456016
2000           9853972  3655437  2466338  2473990
2010-2015 증가율   0.0283   0.0163   0.0982   0.0141

In [113]:
df

특징    지역     2015     2010     2005     2000  2010-2015 증가율
도시명                                                        
서울   수도권  9904312  9631482  9762546  9853972         0.0283
부산   경상권  3448737  3393191  3512547  3655437         0.0163
인천   수도권  2890451  2632035  2517680  2466338         0.0982
대구   경상권  2466052  2431774  2456016  2473990         0.0141

In [117]:
type(df['2010-2015 증가율'])
#데이터프레임의 특정 열(시리즈) 데이터 변경
df['2010-2015 증가율']=df['2010-2015 증가율']*100

In [118]:
df

특징    지역     2015     2010     2005     2000  2010-2015 증가율
도시명                                                        
서울   수도권  9904312  9631482  9762546  9853972           2.83
부산   경상권  3448737  3393191  3512547  3655437           1.63
인천   수도권  2890451  2632035  2517680  2466338           9.82
대구   경상권  2466052  2431774  2456016  2473990           1.41

In [ ]:
#2005-2010증가율 열 추가 = (2010-2005)/2005 * 100
#2010-2015 증가율=(2015-2010)/2010 * 100

In [126]:
df['2005-2010증가율']=((df['2010']-df['2005'])/df['2005']*100).round(2)

In [127]:
df

특징    지역     2015     2010     2005     2000  2010-2015 증가율  2005-2010증가율
도시명                                                                      
서울   수도권  9904312  9631482  9762546  9853972           2.83         -1.34
부산   경상권  3448737  3393191  3512547  3655437           1.63         -3.40
인천   수도권  2890451  2632035  2517680  2466338           9.82          4.54
대구   경상권  2466052  2431774  2456016  2473990           1.41         -0.99

In [128]:
del df['2010-2015 증가율']

In [129]:
df

특징    지역     2015     2010     2005     2000  2005-2010증가율
도시명                                                       
서울   수도권  9904312  9631482  9762546  9853972         -1.34
부산   경상권  3448737  3393191  3512547  3655437         -3.40
인천   수도권  2890451  2632035  2517680  2466338          4.54
대구   경상권  2466052  2431774  2456016  2473990         -0.99

In [134]:
df['지역'] #시리즈
type(df['지역'])
df[['지역']] #데이터프레임

특징    지역
도시명     
서울   수도권
부산   경상권
인천   수도권
대구   경상권

In [139]:
df[['2010','2015']]

특징      2010     2015
도시명                  
서울   9631482  9904312
부산   3393191  3448737
인천   2632035  2890451
대구   2431774  2466052

In [143]:
#2차원 -> 데이터프레임
np.arange(12).reshape(3,4)
df2=pd.DataFrame(np.arange(12).reshape(3,4))
df2
#행,열 인덱스는 자동으로 0번부터 부여

0  1   2   3
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [144]:
df2[2] #2번 index 열에 해당되는 데이터가 추출

0     2
1     6
2    10
Name: 2, dtype: int32

In [145]:
df2[[1,3]]

1   3
0  1   3
1  5   7
2  9  11

In [146]:
df
#행 단위로 데이터 추출 - [시작인덱스:끝인덱스] (끝인덱스-1까지 참조)

특징    지역     2015     2010     2005     2000  2005-2010증가율
도시명                                                       
서울   수도권  9904312  9631482  9762546  9853972         -1.34
부산   경상권  3448737  3393191  3512547  3655437         -3.40
인천   수도권  2890451  2632035  2517680  2466338          4.54
대구   경상권  2466052  2431774  2456016  2473990         -0.99

In [150]:
df[1:2]
df[:2]
df[2:]

특징    지역     2015     2010     2005     2000  2005-2010증가율
도시명                                                       
인천   수도권  2890451  2632035  2517680  2466338          4.54
대구   경상권  2466052  2431774  2456016  2473990         -0.99

In [151]:
df

특징    지역     2015     2010     2005     2000  2005-2010증가율
도시명                                                       
서울   수도권  9904312  9631482  9762546  9853972         -1.34
부산   경상권  3448737  3393191  3512547  3655437         -3.40
인천   수도권  2890451  2632035  2517680  2466338          4.54
대구   경상권  2466052  2431774  2456016  2473990         -0.99

In [156]:
df['서울':]
df['서울':'대구'] #'대구'도 포함됨
df['부산':'인천']
df
df[1:3]

특징    지역     2015     2010     2005     2000  2005-2010증가율
도시명                                                       
부산   경상권  3448737  3393191  3512547  3655437         -3.40
인천   수도권  2890451  2632035  2517680  2466338          4.54

In [164]:
df['2000']['인천'] #df['2000'][2]

2466338

In [165]:
#csv -> dataframe

In [166]:
%%writefile sample1.csv
c1, c2, c3
1, 1.1, one
2, 2.2, two
3, 3.3, three

Writing sample1.csv


In [167]:
pd.read_csv("sample1.csv")

c1   c2      c3
0   1  1.1     one
1   2  2.2     two
2   3  3.3   three

In [168]:
%%writefile sample2.csv
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample2.csv


In [182]:
pd.read_csv("sample2.csv", header=None)
pd.read_csv("sample2.csv", names=['c1','c2','c3'])

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [183]:
#help(pd.read_csv)

In [188]:
pd.read_csv("sample1.csv", index_col='c1') 
#특정열을 행 인덱스로 하고 싶은 경우(int만 가능)

c2      c3
c1             
1   1.1     one
2   2.2     two
3   3.3   three

In [189]:
%%writefile sample3.txt
c1        c2        c3        c4
0.179181 -1.538472  1.347553  0.43381
1.024209  0.087307 -1.281997  0.49265
0.417899 -2.002308  0.255245 -1.10515

Writing sample3.txt


In [192]:
pd.read_table("sample3.txt", sep="\s+")

c1        c2        c3       c4
0  0.179181 -1.538472  1.347553  0.43381
1  1.024209  0.087307 -1.281997  0.49265
2  0.417899 -2.002308  0.255245 -1.10515

In [193]:
%%writefile sample4.txt
파일 제목: sample4.txt
데이터 포맷의 설명:
c1, c2, c3
1, 1.11, one
2, 2.22, two
3, 3.33, three

Writing sample4.txt


In [196]:
pd.read_csv("sample4.txt", skiprows=[0,1])#1번줄과 2번줄을 건너뛰고 읽음

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [197]:
pd.read_csv("sample4.txt", skiprows=2) #맨 위에서 2줄을 건너뛰고 읽음

c1    c2      c3
0   1  1.11     one
1   2  2.22     two
2   3  3.33   three

In [209]:
%%writefile sample5.csv
c1, c2, c3
1, 1.11, one
2,없음, two
누락, 3.33, three

Overwriting sample5.csv


In [213]:
df=pd.read_csv("sample5.csv", na_values=['누락','없음'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   c1      2 non-null      float64
 1    c2     2 non-null      float64
 2    c3     3 non-null      object 
dtypes: float64(2), object(1)
memory usage: 200.0+ bytes


In [215]:
df

c1    c2      c3
0  1.0  1.11     one
1  2.0   NaN     two
2  NaN  3.33   three

In [216]:
#df['c1'][1]+10  #에러

In [222]:
df.to_csv("sample6.csv",index_label=False, sep="$")

In [223]:
!type sample6.csv

c1$ c2$ c3
0$1.0$1.11$ one
1$2.0$$ two
2$$3.33$ three


In [228]:
df.to_csv("sample6.csv", na_rep='누락',encoding='euc-kr')

In [229]:
!type sample6.csv

,c1, c2, c3
0,1.0,1.11, one
1,2.0,누락, two
2,누락,3.33, three


In [231]:
df
df.index=['a','b','c']

In [232]:
df

c1    c2      c3
a  1.0  1.11     one
b  2.0   NaN     two
c  NaN  3.33   three

In [237]:
df.to_csv("sample7.csv", index=False, header=False)

In [238]:
!type sample7.csv

1.0,1.11, one
2.0,, two
,3.33, three


In [ ]:
#pd.read_csv("인터넷상 csv파일 주소")

In [239]:
import datetime

In [249]:
dt_start=datetime.datetime(2020,3,30) # 날짜 데이터 생성

In [256]:
dt_end="2021, 6, 4"

In [253]:
!pip install pandas_datareader
#mport pandas_datareader as pdr

In [257]:
import pandas_datareader as pdr

In [260]:
pdr.get_data_fred(['GDP','CPIAUCSL'],dt_start, dt_end )
#미국 국각총생산, 소비자가격지수

GDP  CPIAUCSL
DATE                           
2020-04-01  19477.444   256.094
2020-05-01        NaN   255.944
2020-06-01        NaN   257.217
2020-07-01  21138.574   258.543
2020-08-01        NaN   259.580
2020-09-01        NaN   260.190
2020-10-01  21477.597   260.352
2020-11-01        NaN   260.721
2020-12-01        NaN   261.564
2021-01-01  22038.226   262.200
2021-02-01        NaN   263.346
2021-03-01        NaN   265.028
2021-04-01  22740.959   266.727
2021-05-01        NaN   268.599
2021-06-01        NaN   270.955

In [ ]:
#finance.yahoo.com

In [261]:
pd.read_csv("TSLA.csv")

Date         Open         High          Low        Close  \
0    2021-03-30   601.750000   637.659973   591.010010   635.619995   
1    2021-03-31   646.619995   672.000000   641.109985   667.929993   
2    2021-04-01   688.369995   692.419983   659.419983   661.750000   
3    2021-04-05   707.710022   708.159973   684.700012   691.049988   
4    2021-04-06   690.299988   696.549988   681.369995   691.619995   
..          ...          ...          ...          ...          ...   
249  2022-03-24  1009.729980  1024.489990   988.799988  1013.919983   
250  2022-03-25  1008.000000  1021.799988   997.320007  1010.640015   
251  2022-03-28  1065.099976  1097.880005  1053.599976  1091.839966   
252  2022-03-29  1107.989990  1114.770020  1073.109985  1099.569946   
253  2022-03-29  1107.989990  1114.760010  1073.109985  1099.569946   

       Adj Close    Volume  
0     635.619995  39432400  
1     667.929993  33337300  
2     661.750000  35298400  
3     691.049988  41842800  
4     691.619995  28271800  
..           ...       ...  
249  1013.919983  22973600  
250  1010.640015  20642900  
251  1091.839966  34168700  
252  1099.569946  24485600  
253  1099.569946  24538273  

[254 rows x 7 columns]

In [262]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                  index=["a", "b", "c"],
                  columns=["A", "B", "C", "D"])

In [263]:
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [265]:
#loc, iloc 속성으로 데이터프레임에 저장된 자료를 조회
#loc:라벨로 데이터 참조
#iloc:정수로 데이터 참조

In [268]:
#df.loc[행 라벨값]
df.loc['a']
df.loc[['a']]

A   B   C   D
a  10  11  12  13

In [ ]:
#df.loc[행 라벨값, 열 라벨값]

In [276]:
df.loc['b':'c'] #df['b':'c'], 연속되어있는 여러 개의 행을 추출
df.loc[['a','c']] #떨어져 있는 여러 개의 행을 추출

A   B   C   D
a  10  11  12  13
c  18  19  20  21

In [279]:
df.A
df['A']

a    10
b    14
c    18
Name: A, dtype: int32

In [283]:
df[df.A>15]

A   B   C   D
c  18  19  20  21

In [284]:
df


A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [285]:
def sr(df):
    return df.A>15

In [286]:
sr(df)

a    False
b    False
c     True
Name: A, dtype: bool

In [287]:
df.loc[sr(df)]

A   B   C   D
c  18  19  20  21

In [288]:
df2 = pd.DataFrame(np.arange(10, 26).reshape(4, 4), columns=["A", "B", "C", "D"])
df2

A   B   C   D
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [302]:
df2.loc[1]
df2.loc[1:3] #라벨?정수?
df2

A   B   C   D
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [308]:
df2.loc[0] #df의 행 인덱스(보이는 번호)
df2.loc[3]
df2.iloc[0] #df의 절대 행 인덱스(보이지 않는 번호, 고유의 번호)
df2.iloc[-1] #맨 뒤에서 1번째 행 추출
df2.loc[-1] #-1 라벨이 있는 행 추출

KeyError: -1

In [300]:
df.iloc[2] #0~2번까지 
df.loc['a']
#df.iloc[3]

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [309]:
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [ ]:
#df에서 A열의 값이 10보다 큰 데이터의 C열과 D열의 값을 추출하시오

In [335]:
df[df.A>10][['C','D']]
#df['A']
df.loc[df.A>10, ['C','D'] ]

C   D
b  16  17
c  20  21

In [336]:
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [340]:
#df에서 11추출
df.loc['a', 'B']
df.loc['a']['B']

11

In [342]:
df.iloc[0, 1]

11

In [345]:
df.iloc[:2, 2]

a    12
b    16
Name: C, dtype: int32

In [346]:
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [350]:
df.iloc[0, 2:4]
df.iloc[0, 2:]

C    12
D    13
Name: a, dtype: int32

In [325]:
df.loc['a', : ]
df.loc[['a','b']][['B','D']]
df.loc[['a','b'],['B','D']]

B   D
a  11  13
b  15  17

In [351]:
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [356]:
df.iloc[2:3, 1:3]

B   C
c  19  20

In [360]:
df.iloc[2:3, -3:]

B   C   D
c  19  20  21

In [362]:
df.iloc[2:3, -3:-1]

B   C
c  19  20

In [365]:
df.iloc[-1]=df.iloc[-1]*2

In [312]:
df.loc['a']['A']
#df.loc[행,열]
df.loc['a', 'A']

10

In [315]:
df.loc['b':]
df.loc['b':,'A']

b    14
c    18
Name: A, dtype: int32

In [367]:
df=pd.read_csv("gapminder.tsv",sep='\t')
df

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [370]:
df.shape
df.shape[0]
df.shape[1]

6

In [371]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [372]:
df.dtypes

country       object
continent     object
year           int64
lifeExp      float64
pop            int64
gdpPercap    float64
dtype: object

In [373]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [374]:
df

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [380]:
df.iloc[:,0]
df['country']
cdf=df.country

In [383]:
cdf.head()
cdf.tail()

1699    Zimbabwe
1700    Zimbabwe
1701    Zimbabwe
1702    Zimbabwe
1703    Zimbabwe
Name: country, dtype: object

In [384]:
df.columns

Index(['country', 'continent', 'year', 'lifeExp', 'pop', 'gdpPercap'], dtype='object')

In [389]:
#'country', 'continent', 'year' 열을 추출하여 subset 변수에 저장
subseet=df.iloc[:,:3]
df[['country', 'continent', 'year']]

country continent  year
0     Afghanistan      Asia  1952
1     Afghanistan      Asia  1957
2     Afghanistan      Asia  1962
3     Afghanistan      Asia  1967
4     Afghanistan      Asia  1972
...           ...       ...   ...
1699     Zimbabwe    Africa  1987
1700     Zimbabwe    Africa  1992
1701     Zimbabwe    Africa  1997
1702     Zimbabwe    Africa  2002
1703     Zimbabwe    Africa  2007

[1704 rows x 3 columns]

In [390]:
df = pd.DataFrame(np.arange(10, 22).reshape(3, 4),
                  index=["a", "b", "c"],
                  columns=["A", "B", "C", "D"])
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [391]:
df.loc['a']

A    10
B    11
C    12
D    13
Name: a, dtype: int32

In [396]:
df.loc['a':'b']
df['a':'b']

A   B   C   D
a  10  11  12  13
b  14  15  16  17

In [395]:
df.loc[['a','b']]

A   B   C   D
a  10  11  12  13
b  14  15  16  17

In [397]:
df

A   B   C   D
a  10  11  12  13
b  14  15  16  17
c  18  19  20  21

In [398]:
#a행과 c행을 추출해봅시다

In [400]:
df.loc[['a','c']]
#df[['a','c']] 에러발생

KeyError: "None of [Index(['a', 'c'], dtype='object')] are in the [columns]"

In [401]:
df2

A   B   C   D
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [405]:
df2.loc[1:2]
#df2.loc['A'] 열을 추출할때는 loc를 빼고 써야 함
df2['A']
df2.A

0    10
1    14
2    18
3    22
Name: A, dtype: int32

In [406]:
df = pd.read_csv('gapminder.tsv', sep='\t')

In [407]:
df.head()

country continent  year  lifeExp       pop   gdpPercap
0  Afghanistan      Asia  1952   28.801   8425333  779.445314
1  Afghanistan      Asia  1957   30.332   9240934  820.853030
2  Afghanistan      Asia  1962   31.997  10267083  853.100710
3  Afghanistan      Asia  1967   34.020  11537966  836.197138
4  Afghanistan      Asia  1972   36.088  13079460  739.981106

In [412]:
df.loc[0]
df.iloc[0]
df.iloc[[0]]
df.iloc[0:1]


country      Afghanistan
continent           Asia
year                1952
lifeExp           28.801
pop              8425333
gdpPercap     779.445314
Name: 0, dtype: object

In [413]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1704 entries, 0 to 1703
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   country    1704 non-null   object 
 1   continent  1704 non-null   object 
 2   year       1704 non-null   int64  
 3   lifeExp    1704 non-null   float64
 4   pop        1704 non-null   int64  
 5   gdpPercap  1704 non-null   float64
dtypes: float64(2), int64(2), object(2)
memory usage: 80.0+ KB


In [418]:
df.iloc[1703]
df.loc[1703]
df.iloc[-1]
#df.loc[-1]

country        Zimbabwe
continent        Africa
year               2007
lifeExp          43.487
pop            12311143
gdpPercap    469.709298
Name: 1703, dtype: object

In [419]:
#0, 99, 999번 자료 추출

In [421]:
df.iloc[[0,99,999]]
df.loc[[0,99,999]]

country continent  year  lifeExp       pop    gdpPercap
0    Afghanistan      Asia  1952   28.801   8425333   779.445314
99    Bangladesh      Asia  1967   43.453  62821884   721.186086
999     Mongolia      Asia  1967   51.253   1149500  1226.041130

In [430]:
df[country]

country continent  year  lifeExp       pop   gdpPercap
0     Afghanistan      Asia  1952   28.801   8425333  779.445314
1     Afghanistan      Asia  1957   30.332   9240934  820.853030
2     Afghanistan      Asia  1962   31.997  10267083  853.100710
3     Afghanistan      Asia  1967   34.020  11537966  836.197138
4     Afghanistan      Asia  1972   36.088  13079460  739.981106
...           ...       ...   ...      ...       ...         ...
1699     Zimbabwe    Africa  1987   62.351   9216418  706.157306
1700     Zimbabwe    Africa  1992   60.377  10704340  693.420786
1701     Zimbabwe    Africa  1997   46.809  11404948  792.449960
1702     Zimbabwe    Africa  2002   39.989  11926563  672.038623
1703     Zimbabwe    Africa  2007   43.487  12311143  469.709298

[1704 rows x 6 columns]

In [426]:
df #year	 pop	gdpPercap 열 추출
df[['year','pop','gdpPercap']]
df.loc[:,['year','pop','gdpPercap']]
df.iloc[:,[2, 4, -1]]

year       pop   gdpPercap
0     1952   8425333  779.445314
1     1957   9240934  820.853030
2     1962  10267083  853.100710
3     1967  11537966  836.197138
4     1972  13079460  739.981106
...    ...       ...         ...
1699  1987   9216418  706.157306
1700  1992  10704340  693.420786
1701  1997  11404948  792.449960
1702  2002  11926563  672.038623
1703  2007  12311143  469.709298

[1704 rows x 3 columns]

In [429]:
df.iloc[:,list(range(5))]
df.iloc[:,list(range(2,5,2))]

df.iloc[:, 0:6:2]

country  year       pop
0     Afghanistan  1952   8425333
1     Afghanistan  1957   9240934
2     Afghanistan  1962  10267083
3     Afghanistan  1967  11537966
4     Afghanistan  1972  13079460
...           ...   ...       ...
1699     Zimbabwe  1987   9216418
1700     Zimbabwe  1992  10704340
1701     Zimbabwe  1997  11404948
1702     Zimbabwe  2002  11926563
1703     Zimbabwe  2007  12311143

[1704 rows x 3 columns]