In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.datasets import load_boston
boston=load_boston()
dfx=pd.DataFrame(boston.data, columns=boston.feature_names)
dfy=pd.DataFrame(boston.target, columns=['MEDV']) #집값

In [3]:
dfx

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [4]:
dfy

MEDV
0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
..    ...
501  22.4
502  20.6
503  23.9
504  22.0
505  11.9

[506 rows x 1 columns]

In [5]:
from sklearn.model_selection import train_test_split
#선형회귀
from sklearn.linear_model import LinearRegression
#MSE
from sklearn.metrics import mean_squared_error
#from statsmodels.formula.api import ols
#선형회귀모델=ols(종속변수~독립변수, 데이터).fit()

In [6]:
xtrain, xtest, ytrain, ytest=train_test_split(dfx, dfy, test_size=0.2, random_state=415)

In [7]:
model=LinearRegression() #선형회귀모델 객체 생성
model.fit(xtrain, ytrain) #학습

LinearRegression()

In [9]:
#h(x) = w1*x1 + w2*x2 + ... + w13*x13 + b
#가중치 확인
model.coef_
#h(x) = -1.08*x1 + 6.89*x2 + ... + -5.56*x13 + 45.567
model.intercept_

array([45.56764299])

In [12]:
#선형회귀모델을 이용하여 테스트 데이터를 예측
xtest

CRIM    ZN  INDUS  CHAS    NOX     RM    AGE     DIS   RAD    TAX  \
202   0.02177  82.5   2.03   0.0  0.415  7.610   15.7  6.2700   2.0  348.0   
426  12.24720   0.0  18.10   0.0  0.584  5.837   59.7  1.9976  24.0  666.0   
154   1.41385   0.0  19.58   1.0  0.871  6.129   96.0  1.7494   5.0  403.0   
96    0.11504   0.0   2.89   0.0  0.445  6.163   69.6  3.4952   2.0  276.0   
317   0.24522   0.0   9.90   0.0  0.544  5.782   71.7  4.0317   4.0  304.0   
..        ...   ...    ...   ...    ...    ...    ...     ...   ...    ...   
494   0.27957   0.0   9.69   0.0  0.585  5.926   42.6  2.3817   6.0  391.0   
382   9.18702   0.0  18.10   0.0  0.700  5.536  100.0  1.5804  24.0  666.0   
397   7.67202   0.0  18.10   0.0  0.693  5.747   98.9  1.6334  24.0  666.0   
18    0.80271   0.0   8.14   0.0  0.538  5.456   36.6  3.7965   4.0  307.0   
184   0.08308   0.0   2.46   0.0  0.488  5.604   89.8  2.9879   3.0  193.0   

     PTRATIO       B  LSTAT  
202     14.7  395.38   3.11  
426     20.2   24.65  15.69  
154     14.7  321.02  15.12  
96      18.0  391.83  11.34  
317     18.4  396.90  15.94  
..       ...     ...    ...  
494     19.2  396.90  13.59  
382     20.2  396.90  23.60  
397     20.2  393.10  19.92  
18      21.0  288.99  11.69  
184     17.8  391.00  13.98  

[102 rows x 13 columns]

In [11]:
pred=model.predict(xtest)
pred

array([[36.724295  ],
       [16.65233967],
       [22.02104896],
       [25.02523539],
       [18.56234896],
       [27.13211593],
       [20.48699645],
       [26.15407851],
       [22.56667524],
       [25.05358754],
       [22.46293233],
       [34.3680539 ],
       [18.99031983],
       [23.82157815],
       [25.08783167],
       [18.18163655],
       [36.0516608 ],
       [18.78377167],
       [12.81023683],
       [19.66584051],
       [23.26698775],
       [25.68040965],
       [16.38561181],
       [ 2.56716777],
       [36.53409391],
       [ 7.24531135],
       [20.56558768],
       [35.54202691],
       [24.70635402],
       [27.87522738],
       [34.13727531],
       [23.27288216],
       [43.65236601],
       [19.64966398],
       [20.53895476],
       [14.09322819],
       [22.79098337],
       [28.22390552],
       [36.45243076],
       [24.29258818],
       [31.34455078],
       [20.96459209],
       [32.39885205],
       [19.64147372],
       [23.90289296],
       [ 8

In [13]:
ytest

MEDV
202  42.3
426  10.2
154  17.0
96   21.4
317  19.8
..    ...
494  24.5
382  11.3
397   8.5
18   20.2
184  26.4

[102 rows x 1 columns]

In [14]:
mse=mean_squared_error(ytest, pred)

In [15]:
mse

29.110741339777846

In [16]:
#당뇨병 데이터를 이용한 당뇨 수치 예측하기

In [17]:
from sklearn import datasets

In [18]:
db_dataset=datasets.load_diabetes()

In [21]:
db_dataset

db_dataset.data
db_dataset.data.shape #(442, 10)

(442, 10)

In [24]:
db_dataset.data
db_dataset.feature_names
xdata=pd.DataFrame(db_dataset.data, columns=db_dataset.feature_names)
xdata

age       sex       bmi        bp        s1        s2        s3  \
0    0.038076  0.050680  0.061696  0.021872 -0.044223 -0.034821 -0.043401   
1   -0.001882 -0.044642 -0.051474 -0.026328 -0.008449 -0.019163  0.074412   
2    0.085299  0.050680  0.044451 -0.005671 -0.045599 -0.034194 -0.032356   
3   -0.089063 -0.044642 -0.011595 -0.036656  0.012191  0.024991 -0.036038   
4    0.005383 -0.044642 -0.036385  0.021872  0.003935  0.015596  0.008142   
..        ...       ...       ...       ...       ...       ...       ...   
437  0.041708  0.050680  0.019662  0.059744 -0.005697 -0.002566 -0.028674   
438 -0.005515  0.050680 -0.015906 -0.067642  0.049341  0.079165 -0.028674   
439  0.041708  0.050680 -0.015906  0.017282 -0.037344 -0.013840 -0.024993   
440 -0.045472 -0.044642  0.039062  0.001215  0.016318  0.015283 -0.028674   
441 -0.045472 -0.044642 -0.073030 -0.081414  0.083740  0.027809  0.173816   

           s4        s5        s6  
0   -0.002592  0.019908 -0.017646  
1   -0.039493 -0.068330 -0.092204  
2   -0.002592  0.002864 -0.025930  
3    0.034309  0.022692 -0.009362  
4   -0.002592 -0.031991 -0.046641  
..        ...       ...       ...  
437 -0.002592  0.031193  0.007207  
438  0.034309 -0.018118  0.044485  
439 -0.011080 -0.046879  0.015491  
440  0.026560  0.044528 -0.025930  
441 -0.039493 -0.004220  0.003064  

[442 rows x 10 columns]

In [26]:
ydata=pd.DataFrame(db_dataset.target, columns=['diabetes'])

In [27]:
ydata

diabetes
0       151.0
1        75.0
2       141.0
3       206.0
4       135.0
..        ...
437     178.0
438     104.0
439     132.0
440     220.0
441      57.0

[442 rows x 1 columns]

In [28]:
xtrain, xtest, ytrain, ytest=train_test_split(xdata, ydata, test_size=0.2, random_state=415)

In [29]:
lr=LinearRegression()#선형회귀모델
lr.fit(xtrain, ytrain)

LinearRegression()

In [33]:
pred=lr.predict(xtest)
pred
#ytest
mse=mean_squared_error(ytest, pred)
mse

2824.9312631157686

In [34]:
# testscore -> 회귀모델생성
# 예측하시오
# 85 87 92 ???
# 72 68 65 ???

In [40]:
df=pd.read_csv("testscore.csv", header=None)
model=LinearRegression()
df

xdata=df.iloc[:,:3]
ydata=df.iloc[:,3]

In [43]:
model.fit(xdata, ydata)

LinearRegression()

In [44]:
test=pd.DataFrame([[85, 87, 92 ], [72, 68, 65]])
test

0   1   2
0  85  87  92
1  72  68  65

In [45]:
model.predict(test)

array([180.522646  , 134.06659892])

In [46]:
#kaggle -> bike sharing demand  -> feature engineering(다중공선성 제거...) => 카페제출